### ISSUE TITLE
`contentId` can't be replaced and is more of a `streamId`

### ISSUE THREAD

**Issue by timalacey** [newrelic/video-agent-roku#66]
Issue 1
`nrAddVideoAttributes()` overrides nrCustomAttributes, meaning `contentId` cannot be overwritten with `nrSetCustomAttribute(m.nr, "contentId", "abcd"))`
https://github.com/newrelic/video-agent-roku/blob/f72903e766363f18150d19dda39d3aacf51abc61/components/NewRelicAgent/NRAgent.brs#L268

Issue 2
The default value for `contentId` relies on the `streamUrl`, making it a `streamId`.
https://github.com/newrelic/video-agent-roku/blob/f72903e766363f18150d19dda39d3aacf51abc61/components/NewRelicAgent/NRAgent.brs#L1064

Context: we have multiple streams per asset. So we want contentId to refer to the assetId of the content, similar to contentTitle.

**Comment by asllop** [comment]
Hi @timalacey , issue 1 is already fixed and will be released soon. Regarding issue 2, `contentId` was designed as a way to facet by stream URL, but using an integer instead of a string, which is more convenient in terms of NRQL performance. But I would like to know more about your specific use case. Is there any property from the video object/metadata that could cover your needs better?
